journal/journal/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from login import views as login_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register', login_views.register, name='register'),
    path('profile', login_views.profile, name='profile'),
    path('login', login_views.login_user, name='login'),
    path('verification/<uidb64>/<token>', login_views.verificate_user, name='verification'),
    path('logout', auth_views.LogoutView.as_view(template_name='login/logout.html'), name='logout'),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journal/main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
# from .models import


urlpatterns = [
    path('', views.index, name='home'),
    path('diary', views.diary, name='diary'),
    path('tasks', views.tasks, name='tasks'),
    path('marks', views.marks, name='marks'),
    path('about', views.about, name='about'),
    path('addmark', views.addmark, name='add-mark'),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

journal/login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('почта'), unique=True)
    father_name = models.CharField(_('отчество'), max_length=254, blank=True, help_text='Если отчества нет, оставьте поле пустым', default="")
    classes = models.CharField(_('классы'), max_length=254, blank=True, help_text="Класс для ученика или классы, которые обучает учитель, если много, пишется через пробел", default="")
    subjects = models.CharField(_('предметы'), max_length=254, blank=True, help_text="Предметы, которые преподаёт учитель, если ученик - оставить пустым", default="")
    is_email_verified = models.BooleanField(_('подтверждённый'), default=False)
    is_teacher = models.BooleanField(_('учитель'), default=False, help_text='Отметье, если пользователь считается учителем')
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return f'{self.user.username} профиль'

journal/login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'last_name', 'first_name', 'father_name', 'password1', 'password2')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'last_name', 'first_name', 'father_name')

journal/login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from .backends import CustomBackend as CB
from .forms import CustomCreationForm
from .models import CustomUser
from .utils import generate_token

from django.views import View
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import EmailMessage, send_mail
from django.conf import settings
from validate_email import validate_email
import smtplib

def send_verification_email(request, user):
    current_site = get_current_site(request)
    email_subject = 'Верификация аккаунта'
    email_body = render_to_string('login/verification.html', {
        'user': user.email,
        'domain': current_site,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': generate_token.make_token(user),
    })
    email = EmailMessage(subject=email_subject, body=email_body, from_email=settings.EMAIL_FROM_USER, to=[user.email])
    email.send()

def login_user(request):
    if request.method == "POST":
        context = {'data': request.POST}
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = CB.authenticate(request, username=email, password=password)

        if user and not user.is_email_verified:
            messages.add_message(request, messages.ERROR,
                                 'Почта не подтверждена, пожалуйста проверьте почту')
            return render(request, 'login/login.html', context)
        
        if user and not user.is_active:
            messages.add_message(request, messages.ERROR,
                                 'Аккаунт ещё не подтверждён администратором, если вы считаете, что это ошибка, напишите в тех. поддержку')
            return render(request, 'login/login.html', context)

        if not user:
            messages.add_message(request, messages.ERROR, 'Неправильная почта или пароль')
            return render(request, 'login/login.html', context)
    
        login(request, user)

        messages.add_message(request, messages.SUCCESS, f'Доброй пожаловать, {user.last_name} {user.first_name}')
        return redirect('diary')
    return render(request, 'login/login.html')

def register(request):
    if request.method == 'POST':
        context = {'has_error': False, 'data': request.POST}
        last_name = request.POST.get('last_name')
        first_name = request.POST.get('first_name')
        email = request.POST.get('email')
        password = request.POST.get('password1')
        password2 = request.POST.get('password2')
    
        if len(password) < 8:
            messages.add_message(request, messages.ERROR,
                                 'Пароль должен быть больше 8 символов')
            context['has_error'] = True

        if password != password2:
            messages.add_message(request, messages.ERROR,
                                 'Пароли не совпадают')
            context['has_error'] = True

        if not validate_email(email):
            messages.add_message(request, messages.ERROR,
                                 'Введена недействительная почта')
            context['has_error'] = True

        if not email:
            messages.add_message(request, messages.ERROR,
                                 'Почта не введена')
            context['has_error'] = True

        if CustomUser.objects.filter(email=email).exists():
            messages.add_message(request, messages.ERROR,
                                 'Такая почта уже зарегистрирована')
            context['has_error'] = True
            return render(request, 'login/register.html', context)

        if context['has_error']:
            return render(request, 'login/register.html', context)
        
        user = CustomUser.objects.create_user(email=email, password=password)
        user.is_active = False
        user.last_name = last_name
        user.first_name = first_name
        user.save()

        if not context['has_error']:
            send_verification_email(request, user)
            messages.add_message(request, messages.SUCCESS, 'Верифицируйте аккаунт, перейдя по ссылке из почты, чтобы продолжить')
            return redirect('login')
        
    return render(request, 'login/register.html')

def verificate_user(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except Exception as e:
        user = None

    if user and generate_token.check_token(user, token):
        user.is_email_verified = True
        user.save()
        
        messages.add_message(request, messages.SUCCESS, 'Вы успешно подтвердили аккаунт, ожидайте подтверждения от администратора')
        return redirect('login')
    
    return render(request, 'login/verification-failed.html', {'user':user})

@login_required
def profile(request):
    return render(request, 'login/profile.html')

journal/login/templates/login/login.html
{% extends "main/base.html" %}
{% block styles %}
<style>

</style>
{% endblock %}
{% block login_errors %}
  {{ error }}
{% endblock %}
{% block login %}
    <div class="content-section" style="max-width: 500px; margin: auto;">
        <form method="POST" autocomplete="on" style="background-color: white;border-radius: 15px; padding: 5px 15px 0;">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="mb-4 text-center">Вход</legend>
                <div id="div_id_email" class="form-group"> 
                    <h6 for="id_email" class="requiredField text-center">Адрес электронной почты<h6> 
                    <div>
                        <input type="text" name="email" autofocus="" autocapitalize="none" autocomplete="email" maxlength="254" class="textinput textInput form-control" required="" id="id_username"> 
                    </div>
                </div>
                <div id="div_id_password" class="form-group">
                    <h6 for="id_password" class="requiredField text-center">Пароль</h6>
                    <div>
                        <input type="password" name="password" autocomplete="current-password" class="textinput textInput form-control" required="" id="id_password">
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-outline-info my-3" type="submit" style="display: block; width: 150px; margin: auto;">Войти</button>
                </div>
            </fieldset>
        </form>
        <div>
            <small class="text-muted" style="display: block; margin-left: 15px;">
                Ещё нет аккаунта? <a class="ml-2" href="{% url 'register' %}">Зарегистрируйся тут!</a>
            </small>
        </div>
    </div>
{% endblock login %}

journal/login/templates/login/logout.html
{% extends "main/base.html" %}
{% block login %}
    <h2>Вы вышли из своей учетной записи</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Войти</a>
        </small>
    </div>
{% endblock login %}

journal/login/templates/login/profile.html
{% extends "main/base.html" %}
{% block styles %}
<style>
  .profile {
    background-color: #fff;
    border-radius: 15px;
    padding: 10px;
  }
  .media-body {
    background-color: #e6e6e6;
    border-radius: 15px;
    padding: 10px;
  }
</style>
{% endblock styles %}
{% block content %}
    <div class="profile">
      <div class="media">
        <div class="media-header">
          <h2 style="display: block; margin-left: 10px;">
            Вы 
            {% if user.is_teacher %}
            учитель
            {% else %}
            ученик
            {% endif %}
          </h2>
        </div>
        <div class="media-body">
          <table>
            <tr>
              <td>Почта</td>
              <td>{{ user.email }}</td>
            </tr>
            <tr>
              <td>ФИО</td>
              <td>{{ user.last_name }} {{ user.first_name }} {{ user.father_name }}</td>
            </tr>
            <tr>
              {% if user.is_teacher %}
                <td>Классы</td>
              {% else %}
                <td>Класс</td>
              {% endif %}
              <td>{{ user.classes }}</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
{% endblock content %}

journal/login/templates/login/register.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block styles %}
<style>
    input:valid {
        outline: 1px solid lightgreen;
    }
    input:invalid {
        outline: 1px solid lightcoral;
    }
</style>
{% endblock styles %}
{% block login %}
    <div class="content-section" style="max-width: 500px; margin: auto;">
        <form method="POST" autocomplete="on" style="background-color: white;border-radius: 15px; padding: 5px 15px 0;">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="mb-4 text-center">Регистрация</legend>
                <div>
                    <div id="div_id_names" class="form-group mb-2">
                        <h6 for="id_names" class=" requiredField text-center">ФИО</h6>
                        <div class="row">
                            <div class="col-12 col-md-4">
                                <input type="text" name="last_name" maxlength="100" autofocus="" class="textinput textInput form-control" required id="id_last_name" placeholder="Фамилия" pattern="[а-яА-ЯёЁ]{1,100}">
                            </div>
                            <div class="col-12 col-md-4">
                                <input type="text" name="first_name" maxlength="100" autofocus="" class="textinput textInput form-control" required id="id_first_name" placeholder="Имя" pattern="[а-яА-ЯёЁ]{1,100}">
                            </div>
                            <div class="col-12 col-md-4">
                                <input type="text" name="father_name" maxlength="100" autofocus="" class="textinput textInput form-control" id="id_father_name" placeholder="Отчество" pattern="[а-яА-ЯёЁ]{1,100}">
                            </div>
                        </div>
                        <small id="hint_id_names" class="form-text text-muted">
                            <ul style="padding: 0;">
                                <li style="line-height: 1.3rem;margin: 0.25rem 0 0 0.45rem;">Пожалуйста указывайте свои настоящие данные</li>
                                <li style="line-height: 1.3rem;margin-left: 0.45rem;">Если у вас нет отчества, оставьте поле пустым</li>
                            </ul>
                        </small>
                    </div>
                    <div id="div_id_email" class="form-group mb-2">
                        <h6 for="id_email" class=" requiredField text-center">Адрес электронной почты</h6>
                        <div>
                            <input type="email" name="email" maxlength="100" autocomplete="username" class="emailinput form-control" required id="id_email" placeholder="*@1543.msk.ru" pattern="[0-9a-zA-Z]+@1543.msk.ru">
                        </div>
                        <small style="margin: 0.25rem 0 0 0.45rem;" id="hint_id_names" class="form-text text-muted">Адрес почты</small>
                    </div>
                    <div id="div_id_password" class="form-group mb-2">
                        <h6 for="id_password" class=" requiredField text-center">Пароль</h6>
                        <div>
                            <input type="password" name="password1" maxlength="100" autocomplete="new-password" class="textinput textInput form-control" required id="id_password" placeholder="Xo0S&)3n" pattern="[a-zA-Z0-9!@#$%&*,.]{8,100}">
                            <small id="hint_id_password" class="form-text text-muted">
                                <ul style="padding: 0;">
                                    <li style="line-height: 1.3rem;margin: 0.25rem 0 0 0.45rem;">Ваш пароль должен содержать от 8 до 100 символов.</li>
                                    <li style="line-height: 1.3rem;margin-left: 0.45rem;">Пароль не должен быть слишком простым и распространенным.</li>
                                    <li style="line-height: 1.3rem;margin-left: 0.45rem;">Пароль не может состоять только из цифр.</li>
                                    <li style="line-height: 1.3rem;margin-left: 0.45rem;">Пароль не может быть таким же, как в поле.</li>
                                </ul>
                            </small>
                        </div>
                    </div>
                    <div id="div_id_password_repeat" class="form-group mb-2">
                        <h6 for="id_password_repeat" class=" requiredField text-center">Подтверждение пароля</h6>
                        <div>
                            <input type="password" name="password2" maxlength="100" class="textinput textInput form-control" required id="id_password_repeat" pattern="[a-zA-Z0-9!@#$%&*,.]{8,255}">
                            <small style="margin: 0.25rem 0 0 0.45rem;" id="hint_id_password_repeat" class="form-text text-muted">Введите пароль ещё раз.</small>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-outline-info my-3" style="display: block;width: 250px; margin: auto;" type="submit">Зарегистрироваться</button>
                </div>
            </fieldset>
        </form>
        <div>
            <small class="text-muted" style="display: block; margin-left: 15px;">
                Уже есть аккаунт? <a class="ml-2" href="{% url 'login' %}">Войдите в него тут!</a>
            </small>
        </div>
    </div>
{% endblock login %}
{% block scripts %}
    <script>
        function hide_errors() {
            document.querySelector('#errors').style.animation = "fadeOutFromBlock 0.5s ease-in-out;";
        }

        function toggleTwoClasses(element, first, second, timeOfAnimation) {
            element.classList.add(second);
            window.setTimeout(function() {
              element.classList.remove(first);
            }, timeOfAnimation);
        }

        window.onload = function() {
            const errors = document.getElementById("errors");
            window.setTimeout(function() { toggleTwoClasses(errors, "is-visible", "is-hidden", 490) }, 15000)
        }
    </script>
{% endblock scripts%}

journal/login/templates/login/verification-failed.html
{% autoescape off %}

<h1>Верификация не прошла успешно</h1>
<p>Возможно вы или кто-то другой уже переходили по этой ссылке, или прошло слишком много времени</p>

{% endautoescape %}

journal/login/templates/login/verification.html
{% autoescape off %}

Здравствуйте, {{ user.last_name }} {{ user.first_name }}

Пожалуйста перейдите по ссылке, чтобы подтвердить свой аккаунт.

http://{{ domain }}{% url 'verification' uidb64=uid token=token %}

{% endautoescape %}